### ISSUE TITLE
feat: RSA key support for git repos

### ISSUE THREAD

**Issue by gdl-reif** [swiftwave-org/swiftwave#1031]
### Is your feature request related to a problem? Please describe

We use Azure DevOps for our git repos, and it only supports RSA deploy keys. 

### Describe the solution you'd like

Allow to select the type of key to generate or store in SwiftWave

### Are you working on this?

Yes

**Comment by tanmoysrt** [comment]
Thanks @gdl-reif for raising the issue. Will check into that.

**Comment by gdl-reif** [comment]
Thanks so much, appreciate it. Would be one of the missing pieces for us to switch to SwiftWave.

**Comment by tanmoysrt** [comment]
Hi @gdl-reif , added support for these type of  private keys for SSH authentication

- RSA
- DSA
- ECDSA256
- ECDSA384
- ECDSA521
- SKECDSA256
- ED25519
- SKED25519

Will be available in this weekend's release.
