### ISSUE TITLE
bug: failed to delete ingress rule if it was prepared for the external service

### ISSUE THREAD

**Issue by vlashchanka** [swiftwave-org/swiftwave#1095]
### Describe the bug

Hi, I was working on preparing the admin part  of my hosted swiftwave instance using this guildeline: https://github.com/orgs/swiftwave-org/discussions/779

I however misconfigured originally  the rules for the subdomain to live on 80 and 443 port, later wanted to use `HTTPS redirect feature`, but it failed as there was a rule defined on the port 80, so I decided to delete both rules, however nothing happens and I get the `failed` status:

<img width="984" alt="image" src="https://github.com/user-attachments/assets/56dd8116-775e-42c2-99d5-38273f1d4048">

I successfully prepared everything which I need at `console.domain.dom`, but still want to make a cleanup and avoid any change I could go to the `http` version. + now I can't delete the `admin.domain.dom` domain.

Could you , please, help?

cc: @tanmoysrt 

### Are you working on this issue?

No

**Comment by tanmoysrt** [comment]
You can delete the domain at port 80, then try to enable https redirection. 

Let me know if you face issue there

**Comment by vlashchanka** [comment]
@tanmoysrt hey, I tried to delete both rules for 80 and 443 ports, no luck.
Domain deletion doesn't work, due to the ingress rules associated:
<img width="461" alt="image" src="https://github.com/user-attachments/assets/4c3bc237-1102-4be6-b105-fe2005df7a5f">

**Comment by tanmoysrt** [comment]
Can you try to delete the ingress rule on port 80 ?
Let me know what's the error it's showing

**Comment by vlashchanka** [comment]
@tanmoysrt could you please elaborate more? Do you mean from the UI? If yes, as I wrote before, doesn't work.

In browser I see `200` status and `{"data":{"deleteIngressRule":true}}` response.

Then on ui it is shown as `Failed` and graphql returns back this:
```ts
            {
                "id": 8,
                "status": "failed",
                "protocol": "http",
                "domain": {
                    "name": "admin.my.domain",
                    "__typename": "Domain"
                },
                "httpsRedirect": false,
                "port": 80,
                "targetType": "externalService",
                "externalService": "172.17.0.1",
                "application": {
                    "name": "",
                    "__typename": "Application"
                },
                "authenticationType": "none",
                "basicAuthAccessControlListName": "",
                "targetPort": 3333,
                "__typename": "IngressRule"
            },

```

**Comment by tanmoysrt** [comment]
@vlashchanka Try one thing
1. For both 80, 443 ingress rule, recreate the ingress rules by `Actions > Recreate & Fix`
2. Wait for changing the status for both of the rules
3. Then, delete both of them one by one
4. Then again add whatever ingress rule you want.

Let me knoe, if it's failing also

**Comment by vlashchanka** [comment]
@tanmoysrt , tried. Nothing changed:
- recreated, became green 🟢 
- tried to delete, first status `deleting`
- after some time `failed` 🔴 

For both.

**Comment by tanmoysrt** [comment]
@vlashchanka 
Then, I need to check the deletion flow, maybe some unhandled case.

I need few infos to find the root cause -
1. Can you provide a list of steps to reproduce/simulate the scenario
2. SSH to your server and grab the haproxy config by
   
   ```bash
   cat /var/lib/swiftwave/haproxy/haproxy.cfg
   ```
   > ⚠️ Please obfuscate domain name, service names in config before sharing
3. Does swiftwave able to generate SSL cert for your domain , what's the status in domain list ?

**Comment by vlashchanka** [comment]
I used this guideline to configure following the described steps:
https://github.com/orgs/swiftwave-org/discussions/779#discussioncomment-9768040

I think this part is suspicious to start from, `adding external services`:
<img width="362" alt="image" src="https://github.com/user-attachments/assets/661ea6c9-aabe-4b57-bdde-1d2e5b53aa00">
I before was trying to setup the application ingress rules and they were deleted without any issues, I would say.

Here is the config, hopefully I removed everything important 😄 :

```txt

global
  chroot /var/lib/haproxy
  user haproxy
  group haproxy
  master-worker
  maxconn 100000
  stats socket /var/run/haproxy.sock user haproxy group haproxy mode 660 level admin expose-fd listeners

defaults unnamed_defaults_1
  mode http
  maxconn 4000
  log global
  option forwardfor
  option tcp-smart-accept
  timeout http-request 10s
  timeout check 10s
  timeout connect 10s
  timeout client 1m
  timeout queue 1m
  timeout server 1m
  timeout http-keep-alive 10s
  retries 3
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http

userlist 01JC3YRW4AS4N0RDPDK84GM3RR

resolvers docker
  nameserver ns1 127.0.0.11:53
  hold nx 30s
  hold obsolete 30s
  hold other 30s
  hold refused 30s
  hold timeout 30s
  hold valid 10s
  timeout resolve 2s
  timeout retry 2s
  accepted_payload_size 8192
  resolve_retries 5

frontend fe_http from unnamed_defaults_1
  mode http
  bind :80
  acl letsencrypt-acl path_beg /.well-known
  http-request redirect scheme https code 301 if { hdr(host) -i redacted1.redacted.domain }
  http-request redirect scheme https code 301 if { hdr(host) -i redacted2.redacted.domain }
  use_backend letsencrypt_backend if letsencrypt-acl
  use_backend be_172.17.0.1_3333 if { hdr(host) -i admin.redacted.domain }
  default_backend error_backend

frontend fe_https from unnamed_defaults_1
  mode http
  bind :443 ssl crt /etc/haproxy/ssl/ alpn h2,http/1.1
  acl letsencrypt-acl path_beg /.well-known
  http-request set-header X-Forwarded-Proto https
  use_backend letsencrypt_backend if letsencrypt-acl
  use_backend be_172.17.0.1_3333 if { hdr(host) -i redacted1.redacted.domain }
  use_backend be_redacted2_3000 if { hdr(host) -i redacted2.redacted.domain }
  use_backend be_172.17.0.1_3333 if { hdr(host) -i admin.redacted.domain }
  default_backend error_backend

backend be_172.17.0.1_3333 from unnamed_defaults_1
  balance roundrobin
  server-template 172.17.0.1_container- 1 172.17.0.1:3333 no-check init-addr none resolvers docker

backend be_redacted2_3000 from unnamed_defaults_1
  balance roundrobin
  server-template redacted2_container- 1 redacted2:3000 no-check init-addr none resolvers docker

backend error_backend from unnamed_defaults_1
  mode http
  http-request deny deny_status 502

backend letsencrypt_backend from unnamed_defaults_1
  option httpchk
  http-check send meth GET uri /healthcheck hdr Host "$SWIFTWAVE_SERVICE_ADDRESS"
  http-check expect status 200
  http-request set-header Host "$SWIFTWAVE_SERVICE_ADDRESS"
  server swiftwave_service_https "$SWIFTWAVE_SERVICE_ENDPOINT" check ssl verify required ca-file /etc/ssl/certs/ca-certificates.crt check-sni "$SWIFTWAVE_SERVICE_ADDRESS" sni str("$SWIFTWAVE_SERVICE_ADDRESS")
  server swiftwave_service_http "$SWIFTWAVE_SERVICE_ENDPOINT" check

program api
  command /dataplaneapi.sh
  no option start-on-reload
```
@tanmoysrt

**Comment by vlashchanka** [comment]
@tanmoysrt, yes, those ssl work fine, I guess:

<img width="784" alt="image" src="https://github.com/user-attachments/assets/f893d463-239a-422c-9153-7c66a02a09fe">

**Comment by tanmoysrt** [comment]
@vlashchanka thanks for providing the info.
Will try to simulate the issue.
I will share the updates here

**Comment by vlashchanka** [comment]
@tanmoysrt also hard to say if this is related issue (sharing just in case it could help):
```shell
Image : redacted.1redacted.domain:3334/6b485e80-870d-4fe4-a982-a75edd5d22c8:e6221bd3-9a44-4bf5-95dc-0b3b142c05c6
Started pushing image to registry
Get "https://redacted1.redacted.domain:3334/v2/": http: server gave HTTP response to HTTPS client


Image push failed
Failed to build application
image push failed
```

Seems that my image registry is not working too, noticed now when I tried to redeploy application. Is it also a known issue, btw? Should something be changed in some config?

**Comment by tanmoysrt** [comment]
Yeah it's normal, as you have changed the config.yml and your domain mappings in ingress not working correctly

**Comment by tanmoysrt** [comment]
You can just revert the overriden config in swiftwave config to fix it

**Comment by vlashchanka** [comment]
`You can just revert the overriden config in swiftwave config to fix it` - how to do this? Could you help?

**Comment by tanmoysrt** [comment]
> `You can just revert the overriden config in swiftwave config to fix it` - how to do this? Could you help?

In the instruction in comment, https://github.com/orgs/swiftwave-org/discussions/779#discussioncomment-9768040
Mark `enabled` key as `false` in `management_node_tunnelling`

**Comment by vlashchanka** [comment]
@tanmoysrt I really appreciate you help 🙇 , seems that your advice with that section config helped to resolve issue with local registry 💪 
<img width="926" alt="image" src="https://github.com/user-attachments/assets/6dfa7b1b-60f9-4c9b-bd44-21ede51d8fda">

Ingress rules, however, haven't found a solution yet.

**Comment by tanmoysrt** [comment]
@vlashchanka didn't get time to check the issue. Will check on the weekend.

**Comment by vlashchanka** [comment]
@tanmoysrt hey, any updates?

**Comment by tanmoysrt** [comment]
> @tanmoysrt hey, any updates?

Found the issue, need some more checks to validate presence of ingress rule.
Will push the fix in next release.

**Comment by vlashchanka** [comment]
Is this a release with the fix?
https://discord.com/channels/1303974360616407107/1304120237989564456/1309214385280909426

**Comment by tanmoysrt** [comment]
> Is this a release with the fix? https://discord.com/channels/1303974360616407107/1304120237989564456/1309214385280909426

No, it's actually contains changes of last week. Last week forget to release the patch actually. so did now.

**Comment by tanmoysrt** [comment]
This weekend I will patch it and release.

**Comment by tanmoysrt** [comment]
Hi @vlashchanka 
Issue fixed. Will do the release soon.

edit: released v2.2.18-1

**Comment by vlashchanka** [comment]
@tanmoysrt , thank you very much for the fix! How to apply it? Should I upgrade to new version, right?

**Comment by vlashchanka** [comment]
I guess, it is autoupgraded somehow, I was able to delete those ingress rules! Once again thank you 🙇

**Comment by tanmoysrt** [comment]
> I guess, it is autoupgraded somehow, I was able to delete those ingress rules! Once again thank you 🙇 

Yeah swiftwave has auto updation in built. So it has upgraded itself ig
