### ISSUE TITLE
Improve github URL Parsing

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#14]
Currently this only supports parsing - https://github.com/The-Debarghya/Pedometer-In-Real-World
We need to add support to parse also - https://github.com/The-Debarghya/Pedometer-In-Real-World.git url

**Comment by The-Debarghya** [comment]
Probable fix can be:
- Using the supported version of `go-git` v5 [(here)](https://github.com/go-git/go-git)

I've tested with both types of links, it's able to clone.
