### ISSUE TITLE
We need to add support for shared storage to available multi-cluster deployment

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#200]

**Comment by prologic** [comment]
How do you intend to add this capability? 🤔

**Comment by tanmoysrt** [comment]
> How do you intend to add this capability? 🤔

I am also exploring the available solutions, docker itself has some driver for zfs, ceph, network storage. I found there is a universal volume driver adapter [rexray](https://github.com/rexray/rexray), it supports various type of cloud storage and provider. Exploring that to understand in a better way.

**Comment by prologic** [comment]
There's also recent support in Swarm for cluster volumes too 👌

**Comment by tanmoysrt** [comment]
> cluster volumes



> There's also recent support in Swarm for cluster volumes too 👌

sure, will check it out

**Comment by tanmoysrt** [comment]
> Swarm for cluster volumes

I was searching for that. I found only this one https://github.com/moby/moby/blob/master/docs/cluster_volumes.md kindof CSI plugins. 

Can you share some resources, if you are talking about something else ?

**Comment by prologic** [comment]
This is what I was referring to.

**Comment by tanmoysrt** [comment]
> This is what I was referring to.

Got it

**Comment by tanmoysrt** [comment]
**Findings -**
1. Rexray team is not maintaining it anymore
2. Docker Swarm Cluster Volume is stable. But most off the providers still not ready for it. CSI plugins are on experimental stage. Good repo to track - https://github.com/olljanat/csi-plugins-for-docker-swarm?tab=readme-ov-file#feature-requestssupport-for-docker-swarm-support-on-existing-csi-plugin-projects

**What to do now ?**
Thiniking to add only support for NFS as shared volume type.
1. AWS has EFS storage , which people can use for NFS mount.
2. Digitalocean also has similiar support.
3. Google cloud also has inbuilt support for creating NFS.

Down the line we can have a inbuilt nfs controller in swiftwave to manage nfs on master nodes , take snapshots (maybe with Restic), just to keep it self contained and simple for home lab setup.

- [x] Tested with docker service if for any reason NFS go down, it itseld restarted , or stuck there, as soon as it backs up , everything come to normal situation

Note : We can add more CSI support after some of the provider release stable CSI plugin for swarm
