### ISSUE TITLE
Persistent volume backup and restore support

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#201]
Description - 
- Support to take backup from UI
- Also can restore that volume via backup file

Track - 
- [x] https://github.com/swiftwave-org/swiftwave/pull/260
- [x] Update the dashboard for backup/restore support https://github.com/swiftwave-org/dashboard/pull/86
- [x] Add support to upload to remote
  - [x] S3 storages [AWS S3, Digitalocean Spaces, Google Storage, Minio(Self Hosted)] https://github.com/swiftwave-org/swiftwave/pull/265

**Comment by prologic** [comment]
Recommend integrating the use of Restic here 👌

**Comment by tanmoysrt** [comment]
> Restic

Thanks ! Will check that.

**Comment by gschurck** [comment]
The specific tool [Docker volume backup](https://github.com/offen/docker-volume-backup) seems interesting to backup Docker volumes, and also supports Docker swarm.

**Comment by tanmoysrt** [comment]
> The specified tool [Docker volume backup](https://github.com/offen/docker-volume-backup) seems interesting to backup Docker volumes, and also supports Docker swarm.

It looks good, will tryout this as well.

I was also trying out similar kind of approach like this, a docker image to export docker volume to *.tar.gz file and also with import support. Link - https://github.com/swiftwave-org/volume-toolkit . Just little bit bash script 😅

Because once we get the backup files, we can handle ourselves to upload to a specific source.

**Comment by tanmoysrt** [comment]
🎉 Persistent Volume backup & restore service has been added.
Backup supports local backup + S3 compaitable storage buckets

**Comment by tanmoysrt** [comment]
> Recommend integrating the use of Restic here 👌

I have tried out this, it's a nice tool for managing snapshots. Will integrate in complete software backup + restore.
