### ISSUE TITLE
optimize docker config generator

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#34]
- [x] If there is no keyword specified, its enough to find the file name
- [x] use double quote `"` for build args. i.e. Replace `PORT=80` with `PORT="80"` #37

**Comment by BRAVO68WEB** [comment]
working on this

**Comment by tanmoysrt** [comment]
Thanks @BRAVO68WEB  for picking up the issue

**Comment by tanmoysrt** [comment]
The issues were fixed
Reference : #81 #56 #55
