### ISSUE TITLE
doubt & query: How can i access it when it run on its own bridge network

### ISSUE THREAD

**Issue by AriaFantom** [swiftwave-org/SwiftWave#48]
### What is your doubt or query?

We really cant access when it not expose to the word in production also i tried it doesnt even show that anything is running on port 80 or not

**Comment by tanmoysrt** [comment]
Hi @AriaFantom , just to confirm, you have used the ` curl -L get.swiftwave.org | bash` command . right ?

**Comment by tanmoysrt** [comment]
Can you share the logs of `swiftwave-app` and `swiftwave-haproxy` container ?

**Comment by AriaFantom** [comment]
Can u please say how can i share those?

**Comment by tanmoysrt** [comment]
> Can u please say how can i share those?

You can run `docker ps` and you will get the list of containers.
Then you can see the container id at the side of container name

Then you use
```
docker logs <container_id>
```
to fetch the logs of the app and haproxy container

**Comment by AriaFantom** [comment]
![image](https://github.com/swiftwave-org/SwiftWave/assets/55119711/28c33648-a9c7-42c1-95d2-ca77c005ec0e)

**Comment by tanmoysrt** [comment]
Run `docker ps -aq` and you can get the stopped containers. From there find out the `app` container and send the logs. It seems that the app container crashed

**Comment by AriaFantom** [comment]
![image](https://github.com/swiftwave-org/SwiftWave/assets/55119711/d8ac634b-a231-4fcb-9df3-8185608dfe5e)

**Comment by tanmoysrt** [comment]
> ![image](https://user-images.githubusercontent.com/55119711/270246356-d8ac634b-a231-4fcb-9df3-8185608dfe5e.png)

this one maybe from `haproxy` container, send the `app` container logs

**Comment by AriaFantom** [comment]
![image](https://github.com/swiftwave-org/SwiftWave/assets/55119711/0abd6e25-8c0a-4c4b-9c5f-587b60140800)

**Comment by tanmoysrt** [comment]
Run `docker service ls` and send a screenshot

**Comment by AriaFantom** [comment]
![image](https://github.com/swiftwave-org/SwiftWave/assets/55119711/adfb144b-7a59-4a56-97b4-8f9cd5cc0336)

**Comment by tanmoysrt** [comment]
> ![image](https://user-images.githubusercontent.com/55119711/270247364-adfb144b-7a59-4a56-97b4-8f9cd5cc0336.png)

Run `docker service logs swiftwave_app` and send the logs

**Comment by AriaFantom** [comment]
![image](https://github.com/swiftwave-org/SwiftWave/assets/55119711/65f7880c-58bd-4e45-ab4c-a55c10b83454)
there is no logs

**Comment by tanmoysrt** [comment]
got it
run `docker image ls` and send a screenshot

**Comment by AriaFantom** [comment]
![image](https://github.com/swiftwave-org/SwiftWave/assets/55119711/56e891a8-75c1-4298-a871-ae93f91eb1b8)

**Comment by tanmoysrt** [comment]
> ![image](https://user-images.githubusercontent.com/55119711/270248173-56e891a8-75c1-4298-a871-ae93f91eb1b8.png)

it seems that it fails to clone the swiftwave image.
Try to pull image manually by
```
docker pull ghcr.io/swiftwave-org/swiftwave:latest
```

and let's see if there is any authentication failure

**Comment by AriaFantom** [comment]
![image](https://github.com/swiftwave-org/SwiftWave/assets/55119711/26d3035a-2620-4854-9434-a1760d9bc31a)

Now i get :/

**Comment by tanmoysrt** [comment]
@AriaFantom we have built the image for amd64 actually, we are making the changes for arm64. We will do this EOD. I will let you know once it get fixed

**Comment by AriaFantom** [comment]
> @AriaFantom we have built the image for amd64 actually, we are making the changes for arm64. We will do this EOD. I will let you know once it get fixed

Ok sure

**Comment by tanmoysrt** [comment]
Tracking by #49

**Comment by tanmoysrt** [comment]
Hi @AriaFantom 
now you can re-run the installation, arm64 images has been added

**Comment by AriaFantom** [comment]
Issue solved
