### ISSUE TITLE
feature: add welcome bot

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#54]
### Describe the solution you'd like
Adding a `welcome bot` is to provide the required information to first-time contributors to Swiftwave. You need to integrate a welcome bot, which will
- On opening the first issue, send a comment welcoming to SwiftWave community and a link to join slack (https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)
- On opening the first PR, congratulate him for his first contribution, and say to join slack and take a review from the other contributors.

### Additional context
You can check this repo to integrate the welcome bot from wow-actions -> https://github.com/wow-actions/welcome .
We are open to suggestions if you would like to use another bot for welcoming purposes.

**Comment by nayangoyal** [comment]
Hi, @tanmoysrt can you assign this issue to me? I want to work on this issue.

**Comment by tanmoysrt** [comment]
> Hi, @tanmoysrt can you assign this issue to me? I want to work on this issue.

Sure, go ahead :+1:

**Comment by nayangoyal** [comment]
Can I submit the pull request after 1 October? For hacktoberfest.

**Comment by tanmoysrt** [comment]
> Can I submit the pull request after 1 October? For hacktoberfest.

Sure, you can raise the PR after 1 October. But you can work anyway locally on the feature.

**Comment by tanmoysrt** [comment]
@nayangoyal  Welcome to SwiftWave Community, Star :star: [the repository ](https://github.com/swiftwave-org/swiftwave) to grow this project and join our slack community [[invite link](https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)] to stay updated.

**Comment by tanmoysrt** [comment]
Closing as we are developing our customized bot https://github.com/swiftwave-org/bot
