### ISSUE TITLE
feature: remove windows os run in ci-lint check

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#60]
### Is your feature request related to a problem? Please describe

CI check in Windows take too much time in Github Actions.

### Describe the solution you'd like

Remove it. MacOS and Ubuntu checks are already there . So it will not have any issue

### Are you working on this?

Yes

**Comment by sculley** [comment]
Hello @tanmoysrt I would like to work on this issue to remove the Windows OS run in the ci-lint Github workflow actions job. Could you assign this to me please?

**Comment by tanmoysrt** [comment]
> Hello @tanmoysrt I would like to work on this issue to remove the Windows OS run in the ci-lint Github workflow actions job. Could you assign this to me please?

Sure, go ahead :+1

**Comment by tanmoysrt** [comment]
@sculley Welcome to SwiftWave Community, Star :star: [the repository ](https://github.com/swiftwave-org/swiftwave) to grow this project and join our slack community [[invite link](https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)] to stay updated.
