### ISSUE TITLE
feat:  memory limiting of deployed applications

### ISSUE THREAD

**Issue by tonislcs** [swiftwave-org/swiftwave#600]
### Is your feature request related to a problem? Please describe

No its not related to any problem really swiftwave wise.

### Describe the solution you'd like

Memory limiting so for application you could set a memory limit (disabled by default) and once it hits that limit restart application this could fix cases where some applications have memory leaks and garbage collector isn't working.

### Are you working on this?

No

**Comment by tanmoysrt** [comment]
We will work on this to add the memory  limit after the initial stable release of v2

**Comment by tanmoysrt** [comment]
Let's implement this.

**Comment by tanmoysrt** [comment]
Done ! Will be available in next release.
