### ISSUE TITLE
feature: integrate commitlint + husky in CI and pre-commit hook setup

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#66]
### Is your feature request related to a problem? Please describe

To maintain a better quality in commit logs, we want to maintain conventional commitlint

### Describe the solution you'd like

1. Integrate commit-lint with husky as a pre-commit hook locally to enforce the checks.
Check out this blog to know more - https://betterprogramming.pub/how-to-lint-commit-messages-with-husky-and-commitlint-b51d20a5e514

2. add a workflow to verify the commit messages in GitHub Actions. 
Reference - https://github.com/conventional-changelog/commitlint

### Are you working on this?

No

**Comment by flushthemoney** [comment]
I would like to work on this issue, kindly assign it to me.

**Comment by tanmoysrt** [comment]
> I would like to work on this issue, kindly assign it to me.
> 

Sure. Go ahead. 

Please raise 2 PRs for this. 
1. First raise a PR for local pre-commit hook setup
2. Second PR for Github Actions setup

**Comment by tanmoysrt** [comment]
@flushthemoney  Welcome to SwiftWave Community, Star :star: [the main repository [swiftwave]](https://github.com/swiftwave-org/swiftwave) to grow this project and join our slack community [[invite link](https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)] to stay updated.

**Comment by flushthemoney** [comment]
@tanmoysrt I have made the first PR with for the local setup. Kindly review it

**Comment by tanmoysrt** [comment]
> @tanmoysrt I have made the first PR with for the local setup. Kindly review it

sure :+1
