### ISSUE TITLE
feature: run `npm install` after git clone

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#68]
### Is your feature request related to a problem? Please describe

We have husky and commit-lint integrated locally to maintain good commit messages.
But if the user doesn't run `npm install`, the pre-commit hook will not be installed, and commit-lint can't be run and later will cause an issue in the CI.

### Describe the solution you'd like

Add a `post-clone` hook natively [without husky or any js library], which will
1. Run `npm install` if nodejs and npm is available
2. Show a message to the user [you can suggest a better message as well]
```
Node.JS NPM or NPX not found. Please install this tool.
After installing Node.JS, run `npm install`
```

**Comment by flushthemoney** [comment]
I would like to solve this issue, please assign it to me.

**Comment by tanmoysrt** [comment]
Closed, as this is going to be part of documentation !
