### ISSUE TITLE
Installscript does not check for wget missing

### ISSUE THREAD

**Issue by Timo-EickGit** [swiftwave-org/swiftwave#8]
the installer does not check if wget is availabe and just fails if its not

**Comment by The-Debarghya** [comment]
Are you facing issues while installing?
If yes, then please can you give the error messages so that we can proceed to fix them.

**Comment by tanmoysrt** [comment]
@Timo-EickGit usually wget comes preinstalled except minimal installation. If you want to work on that issue, you can open the issue in this repository https://github.com/swiftwave-org/installer

**Comment by Timo-EickGit** [comment]
> Are you facing issues while installing? If yes, then please can you give the error messages so that we can proceed to fix them.

the script just cant find files. Is the error i got. 
After checking why i realised that wget was not installed on my debian 12 instance

fix would be doing the same as the installer does for unzip 

``# Check for `wget` command
if ! command -v wget &> /dev/null
then
    echo "wget command could not be found"
    echo "Installing wget..."
    sudo apt update -y
    sudo apt install -y wget
fi`` 

but as @tanmoysrt pointed out this is the wrong repo.
