### ISSUE TITLE
feat: Add Commit Message to Deployment Section

### ISSUE THREAD

**Issue by AnupamKris** [swiftwave-org/swiftwave#860]
Showing the commit message in the deployment section would help in easy understanding of the version of current/past deployments

**Comment by tanmoysrt** [comment]
Moving to main repo, as required changes in backend.

**Comment by tanmoysrt** [comment]
Fixed by https://github.com/swiftwave-org/swiftwave/pull/861 
https://github.com/swiftwave-org/dashboard/issues/213

Thanks @AnupamKris for your contribution
