### ISSUE TITLE
bug: Proxy inconsitency

### ISSUE THREAD

**Issue by samuel-108** [swiftwave-org/swiftwave#907]
### Describe the bug

When operating in cluster mode with multiple servers with multiple IPs, given that I have 2 servers and have 2 domains,

domaina.com -> Server1
domainb.com -> Server2

And server 1 is active proxy while server 2 has it disabled.

Even though server2 has it disabled (updated after it was enabled previously), I can access it over domainb.com but not over domaina.com

<img width="864" alt="Screenshot 2024-07-01 at 1 51 38 AM" src="https://github.com/swiftwave-org/swiftwave/assets/172349572/af91a52c-afd9-4e3d-9ca7-5c4ef785ead2">

### Are you working on this issue?

No

**Comment by tanmoysrt** [comment]
Thanks @samuel-108 for reporting. Will check that.

**Comment by tanmoysrt** [comment]
While you are disabling/enabling proxy, it doesn't do that instantly. It takes around 1~5 minutes to take effect. It does the work  in background.

Currently, I am improving the states in application management, next will check the server management for better experience

**Comment by tanmoysrt** [comment]
Closing it as opened for long time.
Will be patched in next ui revamp.
