### ISSUE TITLE
Bug: No matching versions

### ISSUE THREAD

**Issue by Justman100** [swiftwave-org/swiftwave#981]
### Describe the bug

`CGO_ENABLED=0 go build .`
> warning: GOPATH set to GOROOT (/usr/local/go) has no effect
swiftwave_service/main.go:12:2: no required module provides package github.com/swiftwave-org/swiftwave/swiftwave_service/dashboard; to add it:
        go get github.com/swiftwave-org/swiftwave/swiftwave_service/dashboard

`go get github.com/swiftwave-org/swiftwave/swiftwave_service/dashboard`
>go: github.com/swiftwave-org/swiftwave/swiftwave_service/dashboard: no matching versions for query "upgrade"

### Are you working on this issue?

No

**Comment by tanmoysrt** [comment]
@Justman100 
It looks like dashboard submodule hasn't cloned perfectly. Check that.
Run `make` to run the complete build process.
If you want to manually, check the makefile https://github.com/swiftwave-org/swiftwave/blob/develop/Makefile
